<a href="https://colab.research.google.com/github/GGSimmons1992/UTYV6k8pXAuLL0yL/blob/main/Notebooks/Train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Phase 1b: Classical Random Forest Training

In [14]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.13/dist-packages (2.11.2)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from category_encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.13/dist-packages (from category_encoders) (2.2.3)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category_encoders) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.6.0->category_encoders) (3.1.2)

In [15]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as rf
import pickle
from imblearn.over_sampling import SMOTENC
from os.path import exists
from sklearn.preprocessing import StandardScaler
import category_encoders as ce
from sklearn.feature_selection import chi2
from scipy.stats import spearmanr
import json
from sklearn.metrics import f1_score
from google.colab import drive

drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/SalesReinforcer/Src/')
import dataPrep

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
def splitBetweenTrainAndDev(df):
  train,dev = train_test_split(df,test_size=0.2,random_state=51)
  return train,dev

In [17]:
def trainAndTestModel(model, train, dev):
  model.fit(train.drop(columns=['isSubscribed']), train['isSubscribed'])
  train_predictions = model.predict(train.drop(columns=['isSubscribed']))
  dev_predictions = model.predict(dev.drop(columns=['isSubscribed']))
  trainScore = f1_score(train['isSubscribed'], train_predictions)
  testScore = f1_score(dev['isSubscribed'], dev_predictions)
  return trainScore, testScore

In [18]:
def createModel(criterion, nEstimators, maxDepth, maxFeatures):
  return rf(criterion=criterion, n_estimators=nEstimators, max_depth=maxDepth, max_features=maxFeatures)

In [19]:
def createSortedScoreVsHyperparameterDF(scoreVsHyperparameterDictionary):
  return pd.DataFrame(scoreVsHyperparameterDictionary).sort_values(by=['testScore','trainScore'],ascending=False)

In [20]:
def appendToHyperparameterDictionary(scoreVsHyperparameterDictionary, criterion, nEstimators, maxDepth, maxFeatures, trainScore, testScore):
  scoreVsHyperparameterDictionary['criterion'].append(criterion)
  scoreVsHyperparameterDictionary['nEstimators'].append(nEstimators)
  scoreVsHyperparameterDictionary['maxDepth'].append(maxDepth)
  scoreVsHyperparameterDictionary['maxFeatures'].append(maxFeatures)
  scoreVsHyperparameterDictionary['trainScore'].append(trainScore)
  scoreVsHyperparameterDictionary['testScore'].append(testScore)
  return scoreVsHyperparameterDictionary

In [21]:
def modelExistsInDrive(filename):
  # Drive mounts to /content/drive/My Drive/
  fullName = f"/content/drive/My Drive/Colab Notebooks/SalesReinforcer/Models/{filename}"
  return exists(fullName)

In [22]:
def saveModelToDrive(data,filename):
  # Drive mounts to /content/drive/My Drive/
  fullName = f"/content/drive/My Drive/Colab Notebooks/SalesReinforcer/Models/{filename}"
  pickle.dump(data, open(fullName, 'wb'))

In [23]:
def retrieveModelFromDrive(filename):
  # Drive mounts to /content/drive/My Drive/
  fullName = f"/content/drive/My Drive/Colab Notebooks/SalesReinforcer/Models/{filename}"
  return pickle.load(open(fullName, 'rb'))

In [24]:
def adjustRange(dfColumn):
  # Ensure min and max are called as methods on a pandas Series
  col_min = dfColumn.min()
  col_max = dfColumn.max()

  if col_min != col_max:
    return np.arange(col_min, col_max + 1, 1) # Include col_max in the range

  # Handle the case where all values are the same
  return np.arange(2, 2 * col_max, 1)

In [25]:
def main():
  train = dataPrep.retrieveCSVFromDrive("SalesReinforcerTrain.csv")
  test = dataPrep.retrieveCSVFromDrive("SalesReinforcerTest.csv")
  nColumns = len(train.columns)
  bestTestScore = 0

  possibleCriterion = ["gini","entropy","log_loss"]
  possibleNEstimators = np.arange(5,19, 1)
  possibleMaxDepth = np.arange(2,16,1)
  possibleMaxFeatures = np.arange(2,4,1)

  scoreVsHyperparameterDictionary = {
      "criterion":[],
      "nEstimators":[],
      "maxDepth":[],
      "maxFeatures":[],
      "trainScore":[],
      "testScore":[]
  }
  maxIterations = 2100

  for iteration in range(maxIterations):
    print(f"iteration: {iteration+1} of {maxIterations}")
    criterion = np.random.choice(possibleCriterion)
    nEstimators = np.random.choice(possibleNEstimators)
    maxDepth = np.random.choice(possibleMaxDepth)
    maxFeatures = np.random.choice(possibleMaxFeatures)

    model = createModel(criterion, nEstimators, maxDepth, maxFeatures)
    trainScore, testScore = trainAndTestModel(model, train, test)

    # 1. Unconditionally track and save the overall best model to prevent losing progress
    if (testScore >= bestTestScore):
      bestTestScore = testScore
      saveModelToDrive(model, "baseRandomForest.pkl")
      print(f"-> New best model saved with test score: {testScore:.4f} (train: {trainScore:.4f})")

      if (trainScore >= .75) and (testScore >= .75):
        print("🎉 Target threshold of 0.75 reached!")

    scoreVsHyperparameterDictionary = appendToHyperparameterDictionary(scoreVsHyperparameterDictionary,
                                                                      criterion, nEstimators, maxDepth,
                                                                      maxFeatures, trainScore, testScore)
    if (iteration == (maxIterations-1)):
      df = createSortedScoreVsHyperparameterDF(scoreVsHyperparameterDictionary)
      display(df)
      dataPrep.saveCSVToDrive(df,"BestHyperparameters.csv")
      if (modelExistsInDrive("baseRandomForest.pkl")):
        print('best model found')
      else:
        print('best model not found')
      return

    if (iteration % 10) == 9:
      bestFiveHyperparameterGroups = createSortedScoreVsHyperparameterDF(scoreVsHyperparameterDictionary).head(5)
      display(bestFiveHyperparameterGroups)
      if (bestFiveHyperparameterGroups.iloc[0].testScore >= bestTestScore):
        possibleNEstimators = adjustRange(bestFiveHyperparameterGroups['nEstimators'])
        possibleMaxDepth = adjustRange(bestFiveHyperparameterGroups['maxDepth'])
        possibleMaxFeatures = adjustRange(bestFiveHyperparameterGroups['maxFeatures'])
      if (modelExistsInDrive("baseRandomForest.pkl")):
        testSet = dataPrep.retrieveCSVFromDrive("SalesReinforcerTest.csv")
        bestModel = retrieveModelFromDrive("baseRandomForest.pkl")
        test_predictions = bestModel.predict(testSet.drop(columns=['isSubscribed']))
        current_f1 = f1_score(testSet['isSubscribed'], test_predictions)

        # Early exit only if we hit the desired high-performance threshold of 0.75
        if current_f1 >= 0.75:
          print(f"Target F1 met! Final test score: {current_f1}")
          return

In [26]:
if __name__ == "__main__":
  main()

iteration: 1 of 2100
-> New best model saved with test score: 0.0000 (train: 0.9966)
iteration: 2 of 2100
-> New best model saved with test score: 0.2000 (train: 0.8217)
iteration: 3 of 2100
iteration: 4 of 2100
iteration: 5 of 2100
iteration: 6 of 2100
iteration: 7 of 2100
iteration: 8 of 2100
iteration: 9 of 2100
iteration: 10 of 2100

  criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1  log_loss           10         7            2    0.821693   0.200000
2  log_loss           10         6            2    0.745827   0.142857
8   entropy           12         5            3    0.869405   0.042105
4  log_loss            5         2            2    0.828597   0.014981
6      gini            5        13            3    0.997228   0.000000

iteration: 11 of 2100
iteration: 12 of 2100
iteration: 13 of 2100
iteration: 14 of 2100
iteration: 15 of 2100
iteration: 16 of 2100
iteration: 17 of 2100
iteration: 18 of 2100
iteration: 19 of 2100
iteration: 20 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1   log_loss           10         7            2    0.821693   0.200000
15  log_loss           10         6            3    0.821200   0.153846
2   log_loss           10         6            2    0.745827   0.142857
12  log_loss           12         4            2    0.661183   0.133333
13   entropy           11         4            3    0.817331   0.066667

iteration: 21 of 2100
iteration: 22 of 2100
iteration: 23 of 2100
iteration: 24 of 2100
iteration: 25 of 2100
iteration: 26 of 2100
iteration: 27 of 2100
iteration: 28 of 2100
iteration: 29 of 2100
iteration: 30 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1   log_loss           10         7            2    0.821693   0.200000
15  log_loss           10         6            3    0.821200   0.153846
2   log_loss           10         6            2    0.745827   0.142857
12  log_loss           12         4            2    0.661183   0.133333
13   entropy           11         4            3    0.817331   0.066667

iteration: 31 of 2100
iteration: 32 of 2100
iteration: 33 of 2100
iteration: 34 of 2100
-> New best model saved with test score: 0.2000 (train: 0.8216)
iteration: 35 of 2100
iteration: 36 of 2100
iteration: 37 of 2100
iteration: 38 of 2100
iteration: 39 of 2100
iteration: 40 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000
15  log_loss           10         6            3    0.821200   0.153846
31      gini           11         6            3    0.745986   0.142857
2   log_loss           10         6            2    0.745827   0.142857

iteration: 41 of 2100
iteration: 42 of 2100
iteration: 43 of 2100
iteration: 44 of 2100
iteration: 45 of 2100
iteration: 46 of 2100
iteration: 47 of 2100
iteration: 48 of 2100
iteration: 49 of 2100
iteration: 50 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000
15  log_loss           10         6            3    0.821200   0.153846
31      gini           11         6            3    0.745986   0.142857
2   log_loss           10         6            2    0.745827   0.142857

iteration: 51 of 2100
iteration: 52 of 2100
iteration: 53 of 2100
iteration: 54 of 2100
iteration: 55 of 2100
iteration: 56 of 2100
iteration: 57 of 2100
iteration: 58 of 2100
-> New best model saved with test score: 0.2000 (train: 0.8215)
iteration: 59 of 2100
iteration: 60 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000
57  log_loss           10         6            3    0.821474   0.200000
15  log_loss           10         6            3    0.821200   0.153846
53   entropy           10         6            3    0.947350   0.142857

iteration: 61 of 2100
iteration: 62 of 2100
iteration: 63 of 2100
-> New best model saved with test score: 0.2105 (train: 0.8853)
iteration: 64 of 2100
iteration: 65 of 2100
iteration: 66 of 2100
iteration: 67 of 2100
iteration: 68 of 2100
iteration: 69 of 2100
iteration: 70 of 2100
-> New best model saved with test score: 0.3333 (train: 0.8221)

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69   entropy           10         7            2    0.822077   0.333333
62   entropy           12         6            3    0.885285   0.210526
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000
57  log_loss           10         6            3    0.821474   0.200000

iteration: 71 of 2100
iteration: 72 of 2100
iteration: 73 of 2100
iteration: 74 of 2100
iteration: 75 of 2100
iteration: 76 of 2100
iteration: 77 of 2100
iteration: 78 of 2100
iteration: 79 of 2100
iteration: 80 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69   entropy           10         7            2    0.822077   0.333333
71  log_loss           11         7            3    0.821583   0.250000
62   entropy           12         6            3    0.885285   0.210526
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000

iteration: 81 of 2100
iteration: 82 of 2100
iteration: 83 of 2100
iteration: 84 of 2100
iteration: 85 of 2100
iteration: 86 of 2100
iteration: 87 of 2100
iteration: 88 of 2100
iteration: 89 of 2100
iteration: 90 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69   entropy           10         7            2    0.822077   0.333333
71  log_loss           11         7            3    0.821583   0.250000
62   entropy           12         6            3    0.885285   0.210526
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000

iteration: 91 of 2100
iteration: 92 of 2100
iteration: 93 of 2100
iteration: 94 of 2100
iteration: 95 of 2100
iteration: 96 of 2100
iteration: 97 of 2100
iteration: 98 of 2100
iteration: 99 of 2100
iteration: 100 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69   entropy           10         7            2    0.822077   0.333333
71  log_loss           11         7            3    0.821583   0.250000
62   entropy           12         6            3    0.885285   0.210526
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000

iteration: 101 of 2100
iteration: 102 of 2100
iteration: 103 of 2100
iteration: 104 of 2100
iteration: 105 of 2100
iteration: 106 of 2100
iteration: 107 of 2100
iteration: 108 of 2100
iteration: 109 of 2100
iteration: 110 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69   entropy           10         7            2    0.822077   0.333333
71  log_loss           11         7            3    0.821583   0.250000
62   entropy           12         6            3    0.885285   0.210526
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000

iteration: 111 of 2100
iteration: 112 of 2100
iteration: 113 of 2100
iteration: 114 of 2100
iteration: 115 of 2100
iteration: 116 of 2100
iteration: 117 of 2100
iteration: 118 of 2100
iteration: 119 of 2100
iteration: 120 of 2100

   criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69   entropy           10         7            2    0.822077   0.333333
71  log_loss           11         7            3    0.821583   0.250000
62   entropy           12         6            3    0.885285   0.210526
1   log_loss           10         7            2    0.821693   0.200000
33      gini           12         6            3    0.821583   0.200000

iteration: 121 of 2100
iteration: 122 of 2100
iteration: 123 of 2100
iteration: 124 of 2100
iteration: 125 of 2100
iteration: 126 of 2100
iteration: 127 of 2100
iteration: 128 of 2100
iteration: 129 of 2100
iteration: 130 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69    entropy           10         7            2    0.822077   0.333333
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526
128      gini           10         7            3    0.886846   0.200000
1    log_loss           10         7            2    0.821693   0.200000

iteration: 131 of 2100
iteration: 132 of 2100
iteration: 133 of 2100
iteration: 134 of 2100
iteration: 135 of 2100
iteration: 136 of 2100
iteration: 137 of 2100
iteration: 138 of 2100
iteration: 139 of 2100
iteration: 140 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69    entropy           10         7            2    0.822077   0.333333
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526
128      gini           10         7            3    0.886846   0.200000
1    log_loss           10         7            2    0.821693   0.200000

iteration: 141 of 2100
iteration: 142 of 2100
iteration: 143 of 2100
iteration: 144 of 2100
iteration: 145 of 2100
iteration: 146 of 2100
iteration: 147 of 2100
iteration: 148 of 2100
iteration: 149 of 2100
iteration: 150 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69    entropy           10         7            2    0.822077   0.333333
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526
128      gini           10         7            3    0.886846   0.200000
1    log_loss           10         7            2    0.821693   0.200000

iteration: 151 of 2100
iteration: 152 of 2100
iteration: 153 of 2100
iteration: 154 of 2100
iteration: 155 of 2100
iteration: 156 of 2100
iteration: 157 of 2100
iteration: 158 of 2100
iteration: 159 of 2100
iteration: 160 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69    entropy           10         7            2    0.822077   0.333333
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526
128      gini           10         7            3    0.886846   0.200000
1    log_loss           10         7            2    0.821693   0.200000

iteration: 161 of 2100
iteration: 162 of 2100
iteration: 163 of 2100
iteration: 164 of 2100
iteration: 165 of 2100
iteration: 166 of 2100
iteration: 167 of 2100
iteration: 168 of 2100
iteration: 169 of 2100
iteration: 170 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
69    entropy           10         7            2    0.822077   0.333333
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526
128      gini           10         7            3    0.886846   0.200000
1    log_loss           10         7            2    0.821693   0.200000

iteration: 171 of 2100
iteration: 172 of 2100
iteration: 173 of 2100
iteration: 174 of 2100
iteration: 175 of 2100
iteration: 176 of 2100
iteration: 177 of 2100
iteration: 178 of 2100
iteration: 179 of 2100
iteration: 180 of 2100
-> New best model saved with test score: 0.4000 (train: 0.8222)

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
69    entropy           10         7            2    0.822077   0.333333
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526
128      gini           10         7            3    0.886846   0.200000

iteration: 181 of 2100
iteration: 182 of 2100
iteration: 183 of 2100
iteration: 184 of 2100
iteration: 185 of 2100
iteration: 186 of 2100
iteration: 187 of 2100
iteration: 188 of 2100
iteration: 189 of 2100
iteration: 190 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
69    entropy           10         7            2    0.822077   0.333333
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526
128      gini           10         7            3    0.886846   0.200000

iteration: 191 of 2100
iteration: 192 of 2100
iteration: 193 of 2100
iteration: 194 of 2100
iteration: 195 of 2100
iteration: 196 of 2100
iteration: 197 of 2100
iteration: 198 of 2100
iteration: 199 of 2100
iteration: 200 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526

iteration: 201 of 2100
iteration: 202 of 2100
iteration: 203 of 2100
iteration: 204 of 2100
iteration: 205 of 2100
iteration: 206 of 2100
iteration: 207 of 2100
iteration: 208 of 2100
iteration: 209 of 2100
iteration: 210 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000
62    entropy           12         6            3    0.885285   0.210526

iteration: 211 of 2100
iteration: 212 of 2100
iteration: 213 of 2100
iteration: 214 of 2100
iteration: 215 of 2100
iteration: 216 of 2100
iteration: 217 of 2100
iteration: 218 of 2100
iteration: 219 of 2100
iteration: 220 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 221 of 2100
iteration: 222 of 2100
iteration: 223 of 2100
iteration: 224 of 2100
iteration: 225 of 2100
iteration: 226 of 2100
iteration: 227 of 2100
iteration: 228 of 2100
iteration: 229 of 2100
iteration: 230 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 231 of 2100
iteration: 232 of 2100
iteration: 233 of 2100
iteration: 234 of 2100
iteration: 235 of 2100
iteration: 236 of 2100
iteration: 237 of 2100
iteration: 238 of 2100
iteration: 239 of 2100
iteration: 240 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 241 of 2100
iteration: 242 of 2100
iteration: 243 of 2100
iteration: 244 of 2100
iteration: 245 of 2100
iteration: 246 of 2100
iteration: 247 of 2100
iteration: 248 of 2100
iteration: 249 of 2100
iteration: 250 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 251 of 2100
iteration: 252 of 2100
iteration: 253 of 2100
iteration: 254 of 2100
iteration: 255 of 2100
iteration: 256 of 2100
iteration: 257 of 2100
iteration: 258 of 2100
iteration: 259 of 2100
iteration: 260 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 261 of 2100
iteration: 262 of 2100
iteration: 263 of 2100
iteration: 264 of 2100
iteration: 265 of 2100
iteration: 266 of 2100
iteration: 267 of 2100
iteration: 268 of 2100
iteration: 269 of 2100
iteration: 270 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 271 of 2100
iteration: 272 of 2100
iteration: 273 of 2100
iteration: 274 of 2100
iteration: 275 of 2100
iteration: 276 of 2100
iteration: 277 of 2100
iteration: 278 of 2100
iteration: 279 of 2100
iteration: 280 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 281 of 2100
iteration: 282 of 2100
iteration: 283 of 2100
iteration: 284 of 2100
iteration: 285 of 2100
iteration: 286 of 2100
iteration: 287 of 2100
iteration: 288 of 2100
iteration: 289 of 2100
iteration: 290 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 291 of 2100
iteration: 292 of 2100
iteration: 293 of 2100
iteration: 294 of 2100
iteration: 295 of 2100
iteration: 296 of 2100
iteration: 297 of 2100
iteration: 298 of 2100
iteration: 299 of 2100
iteration: 300 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 301 of 2100
iteration: 302 of 2100
iteration: 303 of 2100
iteration: 304 of 2100
iteration: 305 of 2100
iteration: 306 of 2100
iteration: 307 of 2100
iteration: 308 of 2100
iteration: 309 of 2100
iteration: 310 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 311 of 2100
iteration: 312 of 2100
iteration: 313 of 2100
iteration: 314 of 2100
iteration: 315 of 2100
iteration: 316 of 2100
iteration: 317 of 2100
iteration: 318 of 2100
iteration: 319 of 2100
iteration: 320 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 321 of 2100
iteration: 322 of 2100
iteration: 323 of 2100
iteration: 324 of 2100
iteration: 325 of 2100
iteration: 326 of 2100
iteration: 327 of 2100
iteration: 328 of 2100
iteration: 329 of 2100
iteration: 330 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 331 of 2100
iteration: 332 of 2100
iteration: 333 of 2100
iteration: 334 of 2100
iteration: 335 of 2100
iteration: 336 of 2100
iteration: 337 of 2100
iteration: 338 of 2100
iteration: 339 of 2100
iteration: 340 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 341 of 2100
iteration: 342 of 2100
iteration: 343 of 2100
iteration: 344 of 2100
iteration: 345 of 2100
iteration: 346 of 2100
iteration: 347 of 2100
iteration: 348 of 2100
iteration: 349 of 2100
iteration: 350 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 351 of 2100
iteration: 352 of 2100
iteration: 353 of 2100
iteration: 354 of 2100
iteration: 355 of 2100
iteration: 356 of 2100
iteration: 357 of 2100
iteration: 358 of 2100
iteration: 359 of 2100
iteration: 360 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 361 of 2100
iteration: 362 of 2100
iteration: 363 of 2100
iteration: 364 of 2100
iteration: 365 of 2100
iteration: 366 of 2100
iteration: 367 of 2100
iteration: 368 of 2100
iteration: 369 of 2100
iteration: 370 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 371 of 2100
iteration: 372 of 2100
iteration: 373 of 2100
iteration: 374 of 2100
iteration: 375 of 2100
iteration: 376 of 2100
iteration: 377 of 2100
iteration: 378 of 2100
iteration: 379 of 2100
iteration: 380 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
197   entropy           12         6            2    0.747837   0.285714
71   log_loss           11         7            3    0.821583   0.250000

iteration: 381 of 2100
iteration: 382 of 2100
iteration: 383 of 2100
iteration: 384 of 2100
iteration: 385 of 2100
iteration: 386 of 2100
iteration: 387 of 2100
iteration: 388 of 2100
iteration: 389 of 2100
iteration: 390 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714
197   entropy           12         6            2    0.747837   0.285714

iteration: 391 of 2100
iteration: 392 of 2100
iteration: 393 of 2100
iteration: 394 of 2100
iteration: 395 of 2100
iteration: 396 of 2100
iteration: 397 of 2100
iteration: 398 of 2100
iteration: 399 of 2100
iteration: 400 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714
197   entropy           12         6            2    0.747837   0.285714

iteration: 401 of 2100
iteration: 402 of 2100
iteration: 403 of 2100
iteration: 404 of 2100
iteration: 405 of 2100
iteration: 406 of 2100
iteration: 407 of 2100
iteration: 408 of 2100
iteration: 409 of 2100
iteration: 410 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714
197   entropy           12         6            2    0.747837   0.285714

iteration: 411 of 2100
iteration: 412 of 2100
iteration: 413 of 2100
-> New best model saved with test score: 0.4000 (train: 0.7482)
iteration: 414 of 2100
iteration: 415 of 2100
iteration: 416 of 2100
iteration: 417 of 2100
iteration: 418 of 2100
iteration: 419 of 2100
iteration: 420 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714

iteration: 421 of 2100
iteration: 422 of 2100
iteration: 423 of 2100
iteration: 424 of 2100
iteration: 425 of 2100
iteration: 426 of 2100
iteration: 427 of 2100
iteration: 428 of 2100
iteration: 429 of 2100
iteration: 430 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714

iteration: 431 of 2100
iteration: 432 of 2100
iteration: 433 of 2100
iteration: 434 of 2100
iteration: 435 of 2100
iteration: 436 of 2100
iteration: 437 of 2100
iteration: 438 of 2100
iteration: 439 of 2100
iteration: 440 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714

iteration: 441 of 2100
iteration: 442 of 2100
iteration: 443 of 2100
iteration: 444 of 2100
iteration: 445 of 2100
iteration: 446 of 2100
iteration: 447 of 2100
iteration: 448 of 2100
iteration: 449 of 2100
iteration: 450 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714

iteration: 451 of 2100
iteration: 452 of 2100
iteration: 453 of 2100
iteration: 454 of 2100
iteration: 455 of 2100
iteration: 456 of 2100
iteration: 457 of 2100
iteration: 458 of 2100
iteration: 459 of 2100
iteration: 460 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714

iteration: 461 of 2100
iteration: 462 of 2100
iteration: 463 of 2100
iteration: 464 of 2100
iteration: 465 of 2100
iteration: 466 of 2100
iteration: 467 of 2100
iteration: 468 of 2100
iteration: 469 of 2100
iteration: 470 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714

iteration: 471 of 2100
iteration: 472 of 2100
iteration: 473 of 2100
iteration: 474 of 2100
iteration: 475 of 2100
iteration: 476 of 2100
iteration: 477 of 2100
iteration: 478 of 2100
iteration: 479 of 2100
iteration: 480 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714

iteration: 481 of 2100
iteration: 482 of 2100
iteration: 483 of 2100
iteration: 484 of 2100
iteration: 485 of 2100
iteration: 486 of 2100
iteration: 487 of 2100
iteration: 488 of 2100
iteration: 489 of 2100
iteration: 490 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333
380  log_loss           11         6            3    0.821693   0.285714

iteration: 491 of 2100
iteration: 492 of 2100
iteration: 493 of 2100
iteration: 494 of 2100
iteration: 495 of 2100
-> New best model saved with test score: 0.4000 (train: 0.8875)
iteration: 496 of 2100
iteration: 497 of 2100
iteration: 498 of 2100
iteration: 499 of 2100
iteration: 500 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 501 of 2100
iteration: 502 of 2100
iteration: 503 of 2100
iteration: 504 of 2100
iteration: 505 of 2100
iteration: 506 of 2100
iteration: 507 of 2100
iteration: 508 of 2100
iteration: 509 of 2100
iteration: 510 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 511 of 2100
iteration: 512 of 2100
iteration: 513 of 2100
iteration: 514 of 2100
iteration: 515 of 2100
iteration: 516 of 2100
iteration: 517 of 2100
iteration: 518 of 2100
iteration: 519 of 2100
iteration: 520 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 521 of 2100
iteration: 522 of 2100
iteration: 523 of 2100
iteration: 524 of 2100
iteration: 525 of 2100
iteration: 526 of 2100
iteration: 527 of 2100
iteration: 528 of 2100
iteration: 529 of 2100
iteration: 530 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 531 of 2100
iteration: 532 of 2100
iteration: 533 of 2100
iteration: 534 of 2100
iteration: 535 of 2100
iteration: 536 of 2100
iteration: 537 of 2100
iteration: 538 of 2100
iteration: 539 of 2100
iteration: 540 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 541 of 2100
iteration: 542 of 2100
iteration: 543 of 2100
iteration: 544 of 2100
iteration: 545 of 2100
iteration: 546 of 2100
iteration: 547 of 2100
iteration: 548 of 2100
iteration: 549 of 2100
iteration: 550 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 551 of 2100
iteration: 552 of 2100
iteration: 553 of 2100
iteration: 554 of 2100
iteration: 555 of 2100
iteration: 556 of 2100
iteration: 557 of 2100
iteration: 558 of 2100
iteration: 559 of 2100
iteration: 560 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 561 of 2100
iteration: 562 of 2100
iteration: 563 of 2100
iteration: 564 of 2100
iteration: 565 of 2100
iteration: 566 of 2100
iteration: 567 of 2100
iteration: 568 of 2100
iteration: 569 of 2100
iteration: 570 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 571 of 2100
iteration: 572 of 2100
iteration: 573 of 2100
iteration: 574 of 2100
iteration: 575 of 2100
iteration: 576 of 2100
iteration: 577 of 2100
iteration: 578 of 2100
iteration: 579 of 2100
iteration: 580 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 581 of 2100
iteration: 582 of 2100
iteration: 583 of 2100
iteration: 584 of 2100
iteration: 585 of 2100
iteration: 586 of 2100
iteration: 587 of 2100
iteration: 588 of 2100
iteration: 589 of 2100
iteration: 590 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 591 of 2100
iteration: 592 of 2100
iteration: 593 of 2100
iteration: 594 of 2100
iteration: 595 of 2100
iteration: 596 of 2100
iteration: 597 of 2100
iteration: 598 of 2100
iteration: 599 of 2100
iteration: 600 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 601 of 2100
iteration: 602 of 2100
iteration: 603 of 2100
iteration: 604 of 2100
iteration: 605 of 2100
iteration: 606 of 2100
iteration: 607 of 2100
iteration: 608 of 2100
iteration: 609 of 2100
iteration: 610 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 611 of 2100
iteration: 612 of 2100
iteration: 613 of 2100
iteration: 614 of 2100
iteration: 615 of 2100
iteration: 616 of 2100
iteration: 617 of 2100
iteration: 618 of 2100
iteration: 619 of 2100
iteration: 620 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 621 of 2100
iteration: 622 of 2100
iteration: 623 of 2100
iteration: 624 of 2100
iteration: 625 of 2100
iteration: 626 of 2100
iteration: 627 of 2100
iteration: 628 of 2100
iteration: 629 of 2100
iteration: 630 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333
69    entropy           10         7            2    0.822077   0.333333

iteration: 631 of 2100
iteration: 632 of 2100
iteration: 633 of 2100
iteration: 634 of 2100
iteration: 635 of 2100
iteration: 636 of 2100
iteration: 637 of 2100
iteration: 638 of 2100
iteration: 639 of 2100
iteration: 640 of 2100
-> New best model saved with test score: 0.4000 (train: 0.8220)

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
639  log_loss           10         7            2    0.822022   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333

iteration: 641 of 2100
iteration: 642 of 2100
iteration: 643 of 2100
iteration: 644 of 2100
iteration: 645 of 2100
iteration: 646 of 2100
iteration: 647 of 2100
iteration: 648 of 2100
iteration: 649 of 2100
iteration: 650 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517   0.400000
179      gini           10         6            3    0.822242   0.400000
639  log_loss           10         7            2    0.822022   0.400000
412      gini           12         6            2    0.748156   0.400000
213  log_loss           12         7            2    0.822242   0.333333

iteration: 651 of 2100
iteration: 652 of 2100
iteration: 653 of 2100
iteration: 654 of 2100
iteration: 655 of 2100
iteration: 656 of 2100
iteration: 657 of 2100
iteration: 658 of 2100
-> New best model saved with test score: 0.4000 (train: 0.7475)
iteration: 659 of 2100
iteration: 660 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4
657   entropy           12         7            2    0.747466        0.4

iteration: 661 of 2100
iteration: 662 of 2100
iteration: 663 of 2100
iteration: 664 of 2100
iteration: 665 of 2100
iteration: 666 of 2100
iteration: 667 of 2100
iteration: 668 of 2100
iteration: 669 of 2100
iteration: 670 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4
657   entropy           12         7            2    0.747466        0.4

iteration: 671 of 2100
iteration: 672 of 2100
iteration: 673 of 2100
iteration: 674 of 2100
iteration: 675 of 2100
iteration: 676 of 2100
iteration: 677 of 2100
iteration: 678 of 2100
iteration: 679 of 2100
iteration: 680 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4
657   entropy           12         7            2    0.747466        0.4

iteration: 681 of 2100
iteration: 682 of 2100
iteration: 683 of 2100
iteration: 684 of 2100
iteration: 685 of 2100
iteration: 686 of 2100
iteration: 687 of 2100
iteration: 688 of 2100
iteration: 689 of 2100
iteration: 690 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4
657   entropy           12         7            2    0.747466        0.4

iteration: 691 of 2100
iteration: 692 of 2100
iteration: 693 of 2100
iteration: 694 of 2100
iteration: 695 of 2100
iteration: 696 of 2100
iteration: 697 of 2100
-> New best model saved with test score: 0.4000 (train: 0.7477)
iteration: 698 of 2100
iteration: 699 of 2100
iteration: 700 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4
696   entropy           11         7            3    0.747731        0.4

iteration: 701 of 2100
iteration: 702 of 2100
iteration: 703 of 2100
iteration: 704 of 2100
iteration: 705 of 2100
iteration: 706 of 2100
iteration: 707 of 2100
iteration: 708 of 2100
-> New best model saved with test score: 0.5000 (train: 0.7478)
iteration: 709 of 2100
iteration: 710 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 711 of 2100
iteration: 712 of 2100
iteration: 713 of 2100
iteration: 714 of 2100
iteration: 715 of 2100
iteration: 716 of 2100
iteration: 717 of 2100
iteration: 718 of 2100
iteration: 719 of 2100
iteration: 720 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 721 of 2100
iteration: 722 of 2100
iteration: 723 of 2100
iteration: 724 of 2100
iteration: 725 of 2100
iteration: 726 of 2100
iteration: 727 of 2100
iteration: 728 of 2100
iteration: 729 of 2100
iteration: 730 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 731 of 2100
iteration: 732 of 2100
iteration: 733 of 2100
iteration: 734 of 2100
iteration: 735 of 2100
iteration: 736 of 2100
iteration: 737 of 2100
iteration: 738 of 2100
iteration: 739 of 2100
iteration: 740 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 741 of 2100
iteration: 742 of 2100
iteration: 743 of 2100
iteration: 744 of 2100
iteration: 745 of 2100
iteration: 746 of 2100
iteration: 747 of 2100
iteration: 748 of 2100
iteration: 749 of 2100
iteration: 750 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 751 of 2100
iteration: 752 of 2100
iteration: 753 of 2100
iteration: 754 of 2100
iteration: 755 of 2100
iteration: 756 of 2100
iteration: 757 of 2100
iteration: 758 of 2100
iteration: 759 of 2100
iteration: 760 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 761 of 2100
iteration: 762 of 2100
iteration: 763 of 2100
iteration: 764 of 2100
iteration: 765 of 2100
iteration: 766 of 2100
iteration: 767 of 2100
iteration: 768 of 2100
iteration: 769 of 2100
iteration: 770 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 771 of 2100
iteration: 772 of 2100
iteration: 773 of 2100
iteration: 774 of 2100
iteration: 775 of 2100
iteration: 776 of 2100
iteration: 777 of 2100
iteration: 778 of 2100
iteration: 779 of 2100
iteration: 780 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 781 of 2100
iteration: 782 of 2100
iteration: 783 of 2100
iteration: 784 of 2100
iteration: 785 of 2100
iteration: 786 of 2100
iteration: 787 of 2100
iteration: 788 of 2100
iteration: 789 of 2100
iteration: 790 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 791 of 2100
iteration: 792 of 2100
iteration: 793 of 2100
iteration: 794 of 2100
iteration: 795 of 2100
iteration: 796 of 2100
iteration: 797 of 2100
iteration: 798 of 2100
iteration: 799 of 2100
iteration: 800 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 801 of 2100
iteration: 802 of 2100
iteration: 803 of 2100
iteration: 804 of 2100
iteration: 805 of 2100
iteration: 806 of 2100
iteration: 807 of 2100
iteration: 808 of 2100
iteration: 809 of 2100
iteration: 810 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 811 of 2100
iteration: 812 of 2100
iteration: 813 of 2100
iteration: 814 of 2100
iteration: 815 of 2100
iteration: 816 of 2100
iteration: 817 of 2100
iteration: 818 of 2100
iteration: 819 of 2100
iteration: 820 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 821 of 2100
iteration: 822 of 2100
iteration: 823 of 2100
iteration: 824 of 2100
iteration: 825 of 2100
iteration: 826 of 2100
iteration: 827 of 2100
iteration: 828 of 2100
iteration: 829 of 2100
iteration: 830 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 831 of 2100
iteration: 832 of 2100
iteration: 833 of 2100
iteration: 834 of 2100
iteration: 835 of 2100
iteration: 836 of 2100
iteration: 837 of 2100
iteration: 838 of 2100
iteration: 839 of 2100
iteration: 840 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 841 of 2100
iteration: 842 of 2100
iteration: 843 of 2100
iteration: 844 of 2100
iteration: 845 of 2100
iteration: 846 of 2100
iteration: 847 of 2100
iteration: 848 of 2100
iteration: 849 of 2100
iteration: 850 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 851 of 2100
iteration: 852 of 2100
iteration: 853 of 2100
iteration: 854 of 2100
iteration: 855 of 2100
iteration: 856 of 2100
iteration: 857 of 2100
iteration: 858 of 2100
iteration: 859 of 2100
iteration: 860 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 861 of 2100
iteration: 862 of 2100
iteration: 863 of 2100
iteration: 864 of 2100
iteration: 865 of 2100
iteration: 866 of 2100
iteration: 867 of 2100
iteration: 868 of 2100
iteration: 869 of 2100
iteration: 870 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 871 of 2100
iteration: 872 of 2100
iteration: 873 of 2100
iteration: 874 of 2100
iteration: 875 of 2100
iteration: 876 of 2100
iteration: 877 of 2100
iteration: 878 of 2100
iteration: 879 of 2100
iteration: 880 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 881 of 2100
iteration: 882 of 2100
iteration: 883 of 2100
iteration: 884 of 2100
iteration: 885 of 2100
iteration: 886 of 2100
iteration: 887 of 2100
iteration: 888 of 2100
iteration: 889 of 2100
iteration: 890 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 891 of 2100
iteration: 892 of 2100
iteration: 893 of 2100
iteration: 894 of 2100
iteration: 895 of 2100
iteration: 896 of 2100
iteration: 897 of 2100
iteration: 898 of 2100
iteration: 899 of 2100
iteration: 900 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 901 of 2100
iteration: 902 of 2100
iteration: 903 of 2100
iteration: 904 of 2100
iteration: 905 of 2100
iteration: 906 of 2100
iteration: 907 of 2100
iteration: 908 of 2100
iteration: 909 of 2100
iteration: 910 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 911 of 2100
iteration: 912 of 2100
iteration: 913 of 2100
iteration: 914 of 2100
iteration: 915 of 2100
iteration: 916 of 2100
iteration: 917 of 2100
iteration: 918 of 2100
iteration: 919 of 2100
iteration: 920 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 921 of 2100
iteration: 922 of 2100
iteration: 923 of 2100
iteration: 924 of 2100
iteration: 925 of 2100
iteration: 926 of 2100
iteration: 927 of 2100
iteration: 928 of 2100
iteration: 929 of 2100
iteration: 930 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 931 of 2100
iteration: 932 of 2100
iteration: 933 of 2100
iteration: 934 of 2100
iteration: 935 of 2100
iteration: 936 of 2100
iteration: 937 of 2100
iteration: 938 of 2100
iteration: 939 of 2100
iteration: 940 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 941 of 2100
iteration: 942 of 2100
iteration: 943 of 2100
iteration: 944 of 2100
iteration: 945 of 2100
iteration: 946 of 2100
iteration: 947 of 2100
iteration: 948 of 2100
iteration: 949 of 2100
iteration: 950 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 951 of 2100
iteration: 952 of 2100
iteration: 953 of 2100
iteration: 954 of 2100
iteration: 955 of 2100
iteration: 956 of 2100
iteration: 957 of 2100
iteration: 958 of 2100
iteration: 959 of 2100
iteration: 960 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 961 of 2100
iteration: 962 of 2100
iteration: 963 of 2100
iteration: 964 of 2100
iteration: 965 of 2100
iteration: 966 of 2100
iteration: 967 of 2100
iteration: 968 of 2100
iteration: 969 of 2100
iteration: 970 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 971 of 2100
iteration: 972 of 2100
iteration: 973 of 2100
iteration: 974 of 2100
iteration: 975 of 2100
iteration: 976 of 2100
iteration: 977 of 2100
iteration: 978 of 2100
iteration: 979 of 2100
iteration: 980 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 981 of 2100
iteration: 982 of 2100
iteration: 983 of 2100
iteration: 984 of 2100
iteration: 985 of 2100
iteration: 986 of 2100
iteration: 987 of 2100
iteration: 988 of 2100
iteration: 989 of 2100
iteration: 990 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 991 of 2100
iteration: 992 of 2100
iteration: 993 of 2100
iteration: 994 of 2100
iteration: 995 of 2100
iteration: 996 of 2100
iteration: 997 of 2100
iteration: 998 of 2100
iteration: 999 of 2100
iteration: 1000 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1001 of 2100
iteration: 1002 of 2100
iteration: 1003 of 2100
iteration: 1004 of 2100
iteration: 1005 of 2100
iteration: 1006 of 2100
iteration: 1007 of 2100
iteration: 1008 of 2100
iteration: 1009 of 2100
iteration: 1010 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1011 of 2100
iteration: 1012 of 2100
iteration: 1013 of 2100
iteration: 1014 of 2100
iteration: 1015 of 2100
iteration: 1016 of 2100
iteration: 1017 of 2100
iteration: 1018 of 2100
iteration: 1019 of 2100
iteration: 1020 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1021 of 2100
iteration: 1022 of 2100
iteration: 1023 of 2100
iteration: 1024 of 2100
iteration: 1025 of 2100
iteration: 1026 of 2100
iteration: 1027 of 2100
iteration: 1028 of 2100
iteration: 1029 of 2100
iteration: 1030 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1031 of 2100
iteration: 1032 of 2100
iteration: 1033 of 2100
iteration: 1034 of 2100
iteration: 1035 of 2100
iteration: 1036 of 2100
iteration: 1037 of 2100
iteration: 1038 of 2100
iteration: 1039 of 2100
iteration: 1040 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1041 of 2100
iteration: 1042 of 2100
iteration: 1043 of 2100
iteration: 1044 of 2100
iteration: 1045 of 2100
iteration: 1046 of 2100
iteration: 1047 of 2100
iteration: 1048 of 2100
iteration: 1049 of 2100
iteration: 1050 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1051 of 2100
iteration: 1052 of 2100
iteration: 1053 of 2100
iteration: 1054 of 2100
iteration: 1055 of 2100
iteration: 1056 of 2100
iteration: 1057 of 2100
iteration: 1058 of 2100
iteration: 1059 of 2100
iteration: 1060 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1061 of 2100
iteration: 1062 of 2100
iteration: 1063 of 2100
iteration: 1064 of 2100
iteration: 1065 of 2100
iteration: 1066 of 2100
iteration: 1067 of 2100
iteration: 1068 of 2100
iteration: 1069 of 2100
iteration: 1070 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1071 of 2100
iteration: 1072 of 2100
iteration: 1073 of 2100
iteration: 1074 of 2100
iteration: 1075 of 2100
iteration: 1076 of 2100
iteration: 1077 of 2100
iteration: 1078 of 2100
iteration: 1079 of 2100
iteration: 1080 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1081 of 2100
iteration: 1082 of 2100
iteration: 1083 of 2100
iteration: 1084 of 2100
iteration: 1085 of 2100
iteration: 1086 of 2100
iteration: 1087 of 2100
iteration: 1088 of 2100
iteration: 1089 of 2100
iteration: 1090 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1091 of 2100
iteration: 1092 of 2100
iteration: 1093 of 2100
iteration: 1094 of 2100
iteration: 1095 of 2100
iteration: 1096 of 2100
iteration: 1097 of 2100
iteration: 1098 of 2100
iteration: 1099 of 2100
iteration: 1100 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1101 of 2100
iteration: 1102 of 2100
iteration: 1103 of 2100
iteration: 1104 of 2100
iteration: 1105 of 2100
iteration: 1106 of 2100
iteration: 1107 of 2100
iteration: 1108 of 2100
iteration: 1109 of 2100
iteration: 1110 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1111 of 2100
iteration: 1112 of 2100
iteration: 1113 of 2100
iteration: 1114 of 2100
iteration: 1115 of 2100
iteration: 1116 of 2100
iteration: 1117 of 2100
iteration: 1118 of 2100
iteration: 1119 of 2100
iteration: 1120 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1121 of 2100
iteration: 1122 of 2100
iteration: 1123 of 2100
iteration: 1124 of 2100
iteration: 1125 of 2100
iteration: 1126 of 2100
iteration: 1127 of 2100
iteration: 1128 of 2100
iteration: 1129 of 2100
iteration: 1130 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1131 of 2100
iteration: 1132 of 2100
iteration: 1133 of 2100
iteration: 1134 of 2100
iteration: 1135 of 2100
iteration: 1136 of 2100
iteration: 1137 of 2100
iteration: 1138 of 2100
iteration: 1139 of 2100
iteration: 1140 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1141 of 2100
iteration: 1142 of 2100
iteration: 1143 of 2100
iteration: 1144 of 2100
iteration: 1145 of 2100
iteration: 1146 of 2100
iteration: 1147 of 2100
iteration: 1148 of 2100
iteration: 1149 of 2100
iteration: 1150 of 2100

    criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
707   entropy           11         7            3    0.747837        0.5
494  log_loss           11         7            2    0.887517        0.4
179      gini           10         6            3    0.822242        0.4
639  log_loss           10         7            2    0.822022        0.4
412      gini           12         6            2    0.748156        0.4

iteration: 1151 of 2100
iteration: 1152 of 2100
iteration: 1153 of 2100
iteration: 1154 of 2100
iteration: 1155 of 2100
iteration: 1156 of 2100
iteration: 1157 of 2100
iteration: 1158 of 2100
iteration: 1159 of 2100
iteration: 1160 of 2100
-> New best model saved with test score: 0.5000 (train: 0.7482)

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1161 of 2100
iteration: 1162 of 2100
iteration: 1163 of 2100
iteration: 1164 of 2100
iteration: 1165 of 2100
iteration: 1166 of 2100
iteration: 1167 of 2100
iteration: 1168 of 2100
iteration: 1169 of 2100
iteration: 1170 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1171 of 2100
iteration: 1172 of 2100
iteration: 1173 of 2100
iteration: 1174 of 2100
iteration: 1175 of 2100
iteration: 1176 of 2100
iteration: 1177 of 2100
iteration: 1178 of 2100
iteration: 1179 of 2100
iteration: 1180 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1181 of 2100
iteration: 1182 of 2100
iteration: 1183 of 2100
iteration: 1184 of 2100
iteration: 1185 of 2100
iteration: 1186 of 2100
iteration: 1187 of 2100
iteration: 1188 of 2100
iteration: 1189 of 2100
iteration: 1190 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1191 of 2100
iteration: 1192 of 2100
iteration: 1193 of 2100
iteration: 1194 of 2100
iteration: 1195 of 2100
iteration: 1196 of 2100
iteration: 1197 of 2100
iteration: 1198 of 2100
iteration: 1199 of 2100
iteration: 1200 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1201 of 2100
iteration: 1202 of 2100
iteration: 1203 of 2100
iteration: 1204 of 2100
iteration: 1205 of 2100
iteration: 1206 of 2100
iteration: 1207 of 2100
iteration: 1208 of 2100
iteration: 1209 of 2100
iteration: 1210 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1211 of 2100
iteration: 1212 of 2100
iteration: 1213 of 2100
iteration: 1214 of 2100
iteration: 1215 of 2100
iteration: 1216 of 2100
iteration: 1217 of 2100
iteration: 1218 of 2100
iteration: 1219 of 2100
iteration: 1220 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1221 of 2100
iteration: 1222 of 2100
iteration: 1223 of 2100
iteration: 1224 of 2100
iteration: 1225 of 2100
iteration: 1226 of 2100
iteration: 1227 of 2100
iteration: 1228 of 2100
iteration: 1229 of 2100
iteration: 1230 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1231 of 2100
iteration: 1232 of 2100
iteration: 1233 of 2100
iteration: 1234 of 2100
iteration: 1235 of 2100
iteration: 1236 of 2100
iteration: 1237 of 2100
iteration: 1238 of 2100
iteration: 1239 of 2100
iteration: 1240 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1241 of 2100
iteration: 1242 of 2100
iteration: 1243 of 2100
iteration: 1244 of 2100
iteration: 1245 of 2100
iteration: 1246 of 2100
iteration: 1247 of 2100
iteration: 1248 of 2100
iteration: 1249 of 2100
iteration: 1250 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1251 of 2100
iteration: 1252 of 2100
iteration: 1253 of 2100
iteration: 1254 of 2100
iteration: 1255 of 2100
iteration: 1256 of 2100
iteration: 1257 of 2100
iteration: 1258 of 2100
iteration: 1259 of 2100
iteration: 1260 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1261 of 2100
iteration: 1262 of 2100
iteration: 1263 of 2100
iteration: 1264 of 2100
iteration: 1265 of 2100
iteration: 1266 of 2100
iteration: 1267 of 2100
iteration: 1268 of 2100
iteration: 1269 of 2100
iteration: 1270 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1271 of 2100
iteration: 1272 of 2100
iteration: 1273 of 2100
iteration: 1274 of 2100
iteration: 1275 of 2100
iteration: 1276 of 2100
iteration: 1277 of 2100
iteration: 1278 of 2100
iteration: 1279 of 2100
iteration: 1280 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1281 of 2100
iteration: 1282 of 2100
iteration: 1283 of 2100
iteration: 1284 of 2100
iteration: 1285 of 2100
iteration: 1286 of 2100
iteration: 1287 of 2100
iteration: 1288 of 2100
iteration: 1289 of 2100
iteration: 1290 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1291 of 2100
iteration: 1292 of 2100
iteration: 1293 of 2100
iteration: 1294 of 2100
iteration: 1295 of 2100
iteration: 1296 of 2100
iteration: 1297 of 2100
iteration: 1298 of 2100
iteration: 1299 of 2100
iteration: 1300 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1301 of 2100
iteration: 1302 of 2100
iteration: 1303 of 2100
iteration: 1304 of 2100
iteration: 1305 of 2100
iteration: 1306 of 2100
iteration: 1307 of 2100
iteration: 1308 of 2100
iteration: 1309 of 2100
iteration: 1310 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1311 of 2100
iteration: 1312 of 2100
iteration: 1313 of 2100
iteration: 1314 of 2100
iteration: 1315 of 2100
iteration: 1316 of 2100
iteration: 1317 of 2100
iteration: 1318 of 2100
iteration: 1319 of 2100
iteration: 1320 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1321 of 2100
iteration: 1322 of 2100
iteration: 1323 of 2100
iteration: 1324 of 2100
iteration: 1325 of 2100
iteration: 1326 of 2100
iteration: 1327 of 2100
iteration: 1328 of 2100
iteration: 1329 of 2100
iteration: 1330 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1331 of 2100
iteration: 1332 of 2100
iteration: 1333 of 2100
iteration: 1334 of 2100
iteration: 1335 of 2100
iteration: 1336 of 2100
iteration: 1337 of 2100
iteration: 1338 of 2100
iteration: 1339 of 2100
iteration: 1340 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1341 of 2100
iteration: 1342 of 2100
iteration: 1343 of 2100
iteration: 1344 of 2100
iteration: 1345 of 2100
iteration: 1346 of 2100
iteration: 1347 of 2100
iteration: 1348 of 2100
iteration: 1349 of 2100
iteration: 1350 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1351 of 2100
iteration: 1352 of 2100
iteration: 1353 of 2100
iteration: 1354 of 2100
iteration: 1355 of 2100
iteration: 1356 of 2100
iteration: 1357 of 2100
iteration: 1358 of 2100
iteration: 1359 of 2100
iteration: 1360 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1361 of 2100
iteration: 1362 of 2100
iteration: 1363 of 2100
iteration: 1364 of 2100
iteration: 1365 of 2100
iteration: 1366 of 2100
iteration: 1367 of 2100
iteration: 1368 of 2100
iteration: 1369 of 2100
iteration: 1370 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1371 of 2100
iteration: 1372 of 2100
iteration: 1373 of 2100
iteration: 1374 of 2100
iteration: 1375 of 2100
iteration: 1376 of 2100
iteration: 1377 of 2100
iteration: 1378 of 2100
iteration: 1379 of 2100
iteration: 1380 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1381 of 2100
iteration: 1382 of 2100
iteration: 1383 of 2100
iteration: 1384 of 2100
iteration: 1385 of 2100
iteration: 1386 of 2100
iteration: 1387 of 2100
iteration: 1388 of 2100
iteration: 1389 of 2100
iteration: 1390 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1391 of 2100
iteration: 1392 of 2100
iteration: 1393 of 2100
iteration: 1394 of 2100
iteration: 1395 of 2100
iteration: 1396 of 2100
iteration: 1397 of 2100
iteration: 1398 of 2100
iteration: 1399 of 2100
iteration: 1400 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1401 of 2100
iteration: 1402 of 2100
iteration: 1403 of 2100
iteration: 1404 of 2100
iteration: 1405 of 2100
iteration: 1406 of 2100
iteration: 1407 of 2100
iteration: 1408 of 2100
iteration: 1409 of 2100
iteration: 1410 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1411 of 2100
iteration: 1412 of 2100
iteration: 1413 of 2100
iteration: 1414 of 2100
iteration: 1415 of 2100
iteration: 1416 of 2100
iteration: 1417 of 2100
iteration: 1418 of 2100
iteration: 1419 of 2100
iteration: 1420 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1421 of 2100
iteration: 1422 of 2100
iteration: 1423 of 2100
iteration: 1424 of 2100
iteration: 1425 of 2100
iteration: 1426 of 2100
iteration: 1427 of 2100
iteration: 1428 of 2100
iteration: 1429 of 2100
iteration: 1430 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1431 of 2100
iteration: 1432 of 2100
iteration: 1433 of 2100
iteration: 1434 of 2100
iteration: 1435 of 2100
iteration: 1436 of 2100
iteration: 1437 of 2100
iteration: 1438 of 2100
iteration: 1439 of 2100
iteration: 1440 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1441 of 2100
iteration: 1442 of 2100
iteration: 1443 of 2100
iteration: 1444 of 2100
iteration: 1445 of 2100
iteration: 1446 of 2100
iteration: 1447 of 2100
iteration: 1448 of 2100
iteration: 1449 of 2100
iteration: 1450 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1451 of 2100
iteration: 1452 of 2100
iteration: 1453 of 2100
iteration: 1454 of 2100
iteration: 1455 of 2100
iteration: 1456 of 2100
iteration: 1457 of 2100
iteration: 1458 of 2100
iteration: 1459 of 2100
iteration: 1460 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1461 of 2100
iteration: 1462 of 2100
iteration: 1463 of 2100
iteration: 1464 of 2100
iteration: 1465 of 2100
iteration: 1466 of 2100
iteration: 1467 of 2100
iteration: 1468 of 2100
iteration: 1469 of 2100
iteration: 1470 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1471 of 2100
iteration: 1472 of 2100
iteration: 1473 of 2100
iteration: 1474 of 2100
iteration: 1475 of 2100
iteration: 1476 of 2100
iteration: 1477 of 2100
iteration: 1478 of 2100
iteration: 1479 of 2100
iteration: 1480 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1481 of 2100
iteration: 1482 of 2100
iteration: 1483 of 2100
iteration: 1484 of 2100
iteration: 1485 of 2100
iteration: 1486 of 2100
iteration: 1487 of 2100
iteration: 1488 of 2100
iteration: 1489 of 2100
iteration: 1490 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1491 of 2100
iteration: 1492 of 2100
iteration: 1493 of 2100
iteration: 1494 of 2100
iteration: 1495 of 2100
iteration: 1496 of 2100
iteration: 1497 of 2100
iteration: 1498 of 2100
iteration: 1499 of 2100
iteration: 1500 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1501 of 2100
iteration: 1502 of 2100
iteration: 1503 of 2100
iteration: 1504 of 2100
iteration: 1505 of 2100
iteration: 1506 of 2100
iteration: 1507 of 2100
iteration: 1508 of 2100
iteration: 1509 of 2100
iteration: 1510 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1511 of 2100
iteration: 1512 of 2100
iteration: 1513 of 2100
iteration: 1514 of 2100
iteration: 1515 of 2100
iteration: 1516 of 2100
iteration: 1517 of 2100
iteration: 1518 of 2100
iteration: 1519 of 2100
iteration: 1520 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1521 of 2100
iteration: 1522 of 2100
iteration: 1523 of 2100
iteration: 1524 of 2100
iteration: 1525 of 2100
iteration: 1526 of 2100
iteration: 1527 of 2100
iteration: 1528 of 2100
iteration: 1529 of 2100
iteration: 1530 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1531 of 2100
iteration: 1532 of 2100
iteration: 1533 of 2100
iteration: 1534 of 2100
iteration: 1535 of 2100
iteration: 1536 of 2100
iteration: 1537 of 2100
iteration: 1538 of 2100
iteration: 1539 of 2100
iteration: 1540 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1541 of 2100
iteration: 1542 of 2100
iteration: 1543 of 2100
iteration: 1544 of 2100
iteration: 1545 of 2100
iteration: 1546 of 2100
iteration: 1547 of 2100
iteration: 1548 of 2100
iteration: 1549 of 2100
iteration: 1550 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1551 of 2100
iteration: 1552 of 2100
iteration: 1553 of 2100
iteration: 1554 of 2100
iteration: 1555 of 2100
iteration: 1556 of 2100
iteration: 1557 of 2100
iteration: 1558 of 2100
iteration: 1559 of 2100
iteration: 1560 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1561 of 2100
iteration: 1562 of 2100
iteration: 1563 of 2100
iteration: 1564 of 2100
iteration: 1565 of 2100
iteration: 1566 of 2100
iteration: 1567 of 2100
iteration: 1568 of 2100
iteration: 1569 of 2100
iteration: 1570 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1571 of 2100
iteration: 1572 of 2100
iteration: 1573 of 2100
iteration: 1574 of 2100
iteration: 1575 of 2100
iteration: 1576 of 2100
iteration: 1577 of 2100
iteration: 1578 of 2100
iteration: 1579 of 2100
iteration: 1580 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1581 of 2100
iteration: 1582 of 2100
iteration: 1583 of 2100
iteration: 1584 of 2100
iteration: 1585 of 2100
iteration: 1586 of 2100
iteration: 1587 of 2100
iteration: 1588 of 2100
iteration: 1589 of 2100
iteration: 1590 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1591 of 2100
iteration: 1592 of 2100
iteration: 1593 of 2100
iteration: 1594 of 2100
iteration: 1595 of 2100
iteration: 1596 of 2100
iteration: 1597 of 2100
iteration: 1598 of 2100
iteration: 1599 of 2100
iteration: 1600 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1601 of 2100
iteration: 1602 of 2100
iteration: 1603 of 2100
iteration: 1604 of 2100
iteration: 1605 of 2100
iteration: 1606 of 2100
iteration: 1607 of 2100
iteration: 1608 of 2100
iteration: 1609 of 2100
iteration: 1610 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1611 of 2100
iteration: 1612 of 2100
iteration: 1613 of 2100
iteration: 1614 of 2100
iteration: 1615 of 2100
iteration: 1616 of 2100
iteration: 1617 of 2100
iteration: 1618 of 2100
iteration: 1619 of 2100
iteration: 1620 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1621 of 2100
iteration: 1622 of 2100
iteration: 1623 of 2100
iteration: 1624 of 2100
iteration: 1625 of 2100
iteration: 1626 of 2100
iteration: 1627 of 2100
iteration: 1628 of 2100
iteration: 1629 of 2100
iteration: 1630 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1631 of 2100
iteration: 1632 of 2100
iteration: 1633 of 2100
iteration: 1634 of 2100
iteration: 1635 of 2100
iteration: 1636 of 2100
iteration: 1637 of 2100
iteration: 1638 of 2100
iteration: 1639 of 2100
iteration: 1640 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1641 of 2100
iteration: 1642 of 2100
iteration: 1643 of 2100
iteration: 1644 of 2100
iteration: 1645 of 2100
iteration: 1646 of 2100
iteration: 1647 of 2100
iteration: 1648 of 2100
iteration: 1649 of 2100
iteration: 1650 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1651 of 2100
iteration: 1652 of 2100
iteration: 1653 of 2100
iteration: 1654 of 2100
iteration: 1655 of 2100
iteration: 1656 of 2100
iteration: 1657 of 2100
iteration: 1658 of 2100
iteration: 1659 of 2100
iteration: 1660 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1661 of 2100
iteration: 1662 of 2100
iteration: 1663 of 2100
iteration: 1664 of 2100
iteration: 1665 of 2100
iteration: 1666 of 2100
iteration: 1667 of 2100
iteration: 1668 of 2100
iteration: 1669 of 2100
iteration: 1670 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1671 of 2100
iteration: 1672 of 2100
iteration: 1673 of 2100
iteration: 1674 of 2100
iteration: 1675 of 2100
iteration: 1676 of 2100
iteration: 1677 of 2100
iteration: 1678 of 2100
iteration: 1679 of 2100
iteration: 1680 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1681 of 2100
iteration: 1682 of 2100
iteration: 1683 of 2100
iteration: 1684 of 2100
iteration: 1685 of 2100
iteration: 1686 of 2100
iteration: 1687 of 2100
iteration: 1688 of 2100
iteration: 1689 of 2100
iteration: 1690 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1691 of 2100
iteration: 1692 of 2100
iteration: 1693 of 2100
iteration: 1694 of 2100
iteration: 1695 of 2100
iteration: 1696 of 2100
iteration: 1697 of 2100
iteration: 1698 of 2100
iteration: 1699 of 2100
iteration: 1700 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1701 of 2100
iteration: 1702 of 2100
iteration: 1703 of 2100
iteration: 1704 of 2100
iteration: 1705 of 2100
iteration: 1706 of 2100
iteration: 1707 of 2100
iteration: 1708 of 2100
iteration: 1709 of 2100
iteration: 1710 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1711 of 2100
iteration: 1712 of 2100
iteration: 1713 of 2100
iteration: 1714 of 2100
iteration: 1715 of 2100
iteration: 1716 of 2100
iteration: 1717 of 2100
iteration: 1718 of 2100
iteration: 1719 of 2100
iteration: 1720 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1721 of 2100
iteration: 1722 of 2100
iteration: 1723 of 2100
iteration: 1724 of 2100
iteration: 1725 of 2100
iteration: 1726 of 2100
iteration: 1727 of 2100
iteration: 1728 of 2100
iteration: 1729 of 2100
iteration: 1730 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1731 of 2100
iteration: 1732 of 2100
iteration: 1733 of 2100
iteration: 1734 of 2100
iteration: 1735 of 2100
iteration: 1736 of 2100
iteration: 1737 of 2100
iteration: 1738 of 2100
iteration: 1739 of 2100
iteration: 1740 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1741 of 2100
iteration: 1742 of 2100
iteration: 1743 of 2100
iteration: 1744 of 2100
iteration: 1745 of 2100
iteration: 1746 of 2100
iteration: 1747 of 2100
iteration: 1748 of 2100
iteration: 1749 of 2100
iteration: 1750 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1751 of 2100
iteration: 1752 of 2100
iteration: 1753 of 2100
iteration: 1754 of 2100
iteration: 1755 of 2100
iteration: 1756 of 2100
iteration: 1757 of 2100
iteration: 1758 of 2100
iteration: 1759 of 2100
iteration: 1760 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1761 of 2100
iteration: 1762 of 2100
iteration: 1763 of 2100
iteration: 1764 of 2100
iteration: 1765 of 2100
iteration: 1766 of 2100
iteration: 1767 of 2100
iteration: 1768 of 2100
iteration: 1769 of 2100
iteration: 1770 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1771 of 2100
iteration: 1772 of 2100
iteration: 1773 of 2100
iteration: 1774 of 2100
iteration: 1775 of 2100
iteration: 1776 of 2100
iteration: 1777 of 2100
iteration: 1778 of 2100
iteration: 1779 of 2100
iteration: 1780 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1781 of 2100
iteration: 1782 of 2100
iteration: 1783 of 2100
iteration: 1784 of 2100
iteration: 1785 of 2100
iteration: 1786 of 2100
iteration: 1787 of 2100
iteration: 1788 of 2100
iteration: 1789 of 2100
iteration: 1790 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1791 of 2100
iteration: 1792 of 2100
iteration: 1793 of 2100
iteration: 1794 of 2100
iteration: 1795 of 2100
iteration: 1796 of 2100
iteration: 1797 of 2100
iteration: 1798 of 2100
iteration: 1799 of 2100
iteration: 1800 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1801 of 2100
iteration: 1802 of 2100
iteration: 1803 of 2100
iteration: 1804 of 2100
iteration: 1805 of 2100
iteration: 1806 of 2100
iteration: 1807 of 2100
iteration: 1808 of 2100
iteration: 1809 of 2100
iteration: 1810 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1811 of 2100
iteration: 1812 of 2100
iteration: 1813 of 2100
iteration: 1814 of 2100
iteration: 1815 of 2100
iteration: 1816 of 2100
iteration: 1817 of 2100
iteration: 1818 of 2100
iteration: 1819 of 2100
iteration: 1820 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1821 of 2100
iteration: 1822 of 2100
iteration: 1823 of 2100
iteration: 1824 of 2100
iteration: 1825 of 2100
iteration: 1826 of 2100
iteration: 1827 of 2100
iteration: 1828 of 2100
iteration: 1829 of 2100
iteration: 1830 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1831 of 2100
iteration: 1832 of 2100
iteration: 1833 of 2100
iteration: 1834 of 2100
iteration: 1835 of 2100
iteration: 1836 of 2100
iteration: 1837 of 2100
iteration: 1838 of 2100
iteration: 1839 of 2100
iteration: 1840 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1841 of 2100
iteration: 1842 of 2100
iteration: 1843 of 2100
iteration: 1844 of 2100
iteration: 1845 of 2100
iteration: 1846 of 2100
iteration: 1847 of 2100
iteration: 1848 of 2100
iteration: 1849 of 2100
iteration: 1850 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1851 of 2100
iteration: 1852 of 2100
iteration: 1853 of 2100
iteration: 1854 of 2100
iteration: 1855 of 2100
iteration: 1856 of 2100
iteration: 1857 of 2100
iteration: 1858 of 2100
iteration: 1859 of 2100
iteration: 1860 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1861 of 2100
iteration: 1862 of 2100
iteration: 1863 of 2100
iteration: 1864 of 2100
iteration: 1865 of 2100
iteration: 1866 of 2100
iteration: 1867 of 2100
iteration: 1868 of 2100
iteration: 1869 of 2100
iteration: 1870 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1871 of 2100
iteration: 1872 of 2100
iteration: 1873 of 2100
iteration: 1874 of 2100
iteration: 1875 of 2100
iteration: 1876 of 2100
iteration: 1877 of 2100
iteration: 1878 of 2100
iteration: 1879 of 2100
iteration: 1880 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1881 of 2100
iteration: 1882 of 2100
iteration: 1883 of 2100
iteration: 1884 of 2100
iteration: 1885 of 2100
iteration: 1886 of 2100
iteration: 1887 of 2100
iteration: 1888 of 2100
iteration: 1889 of 2100
iteration: 1890 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1891 of 2100
iteration: 1892 of 2100
iteration: 1893 of 2100
iteration: 1894 of 2100
iteration: 1895 of 2100
iteration: 1896 of 2100
iteration: 1897 of 2100
iteration: 1898 of 2100
iteration: 1899 of 2100
iteration: 1900 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1901 of 2100
iteration: 1902 of 2100
iteration: 1903 of 2100
iteration: 1904 of 2100
iteration: 1905 of 2100
iteration: 1906 of 2100
iteration: 1907 of 2100
iteration: 1908 of 2100
iteration: 1909 of 2100
iteration: 1910 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1911 of 2100
iteration: 1912 of 2100
iteration: 1913 of 2100
iteration: 1914 of 2100
iteration: 1915 of 2100
iteration: 1916 of 2100
iteration: 1917 of 2100
iteration: 1918 of 2100
iteration: 1919 of 2100
iteration: 1920 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1921 of 2100
iteration: 1922 of 2100
iteration: 1923 of 2100
iteration: 1924 of 2100
iteration: 1925 of 2100
iteration: 1926 of 2100
iteration: 1927 of 2100
iteration: 1928 of 2100
iteration: 1929 of 2100
iteration: 1930 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1931 of 2100
iteration: 1932 of 2100
iteration: 1933 of 2100
iteration: 1934 of 2100
iteration: 1935 of 2100
iteration: 1936 of 2100
iteration: 1937 of 2100
iteration: 1938 of 2100
iteration: 1939 of 2100
iteration: 1940 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1941 of 2100
iteration: 1942 of 2100
iteration: 1943 of 2100
iteration: 1944 of 2100
iteration: 1945 of 2100
iteration: 1946 of 2100
iteration: 1947 of 2100
iteration: 1948 of 2100
iteration: 1949 of 2100
iteration: 1950 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
639   log_loss           10         7            2    0.822022        0.4

iteration: 1951 of 2100
iteration: 1952 of 2100
iteration: 1953 of 2100
iteration: 1954 of 2100
iteration: 1955 of 2100
iteration: 1956 of 2100
iteration: 1957 of 2100
-> New best model saved with test score: 0.5000 (train: 0.7477)
iteration: 1958 of 2100
iteration: 1959 of 2100
iteration: 1960 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 1961 of 2100
iteration: 1962 of 2100
iteration: 1963 of 2100
iteration: 1964 of 2100
iteration: 1965 of 2100
iteration: 1966 of 2100
iteration: 1967 of 2100
iteration: 1968 of 2100
iteration: 1969 of 2100
iteration: 1970 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 1971 of 2100
iteration: 1972 of 2100
iteration: 1973 of 2100
iteration: 1974 of 2100
iteration: 1975 of 2100
iteration: 1976 of 2100
iteration: 1977 of 2100
iteration: 1978 of 2100
iteration: 1979 of 2100
iteration: 1980 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 1981 of 2100
iteration: 1982 of 2100
iteration: 1983 of 2100
iteration: 1984 of 2100
iteration: 1985 of 2100
iteration: 1986 of 2100
iteration: 1987 of 2100
iteration: 1988 of 2100
iteration: 1989 of 2100
iteration: 1990 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 1991 of 2100
iteration: 1992 of 2100
iteration: 1993 of 2100
iteration: 1994 of 2100
iteration: 1995 of 2100
iteration: 1996 of 2100
iteration: 1997 of 2100
iteration: 1998 of 2100
iteration: 1999 of 2100
iteration: 2000 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2001 of 2100
iteration: 2002 of 2100
iteration: 2003 of 2100
iteration: 2004 of 2100
iteration: 2005 of 2100
iteration: 2006 of 2100
iteration: 2007 of 2100
iteration: 2008 of 2100
iteration: 2009 of 2100
iteration: 2010 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2011 of 2100
iteration: 2012 of 2100
iteration: 2013 of 2100
iteration: 2014 of 2100
iteration: 2015 of 2100
iteration: 2016 of 2100
iteration: 2017 of 2100
iteration: 2018 of 2100
iteration: 2019 of 2100
iteration: 2020 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2021 of 2100
iteration: 2022 of 2100
iteration: 2023 of 2100
iteration: 2024 of 2100
iteration: 2025 of 2100
iteration: 2026 of 2100
iteration: 2027 of 2100
iteration: 2028 of 2100
iteration: 2029 of 2100
iteration: 2030 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2031 of 2100
iteration: 2032 of 2100
iteration: 2033 of 2100
iteration: 2034 of 2100
iteration: 2035 of 2100
iteration: 2036 of 2100
iteration: 2037 of 2100
iteration: 2038 of 2100
iteration: 2039 of 2100
iteration: 2040 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2041 of 2100
iteration: 2042 of 2100
iteration: 2043 of 2100
iteration: 2044 of 2100
iteration: 2045 of 2100
iteration: 2046 of 2100
iteration: 2047 of 2100
iteration: 2048 of 2100
iteration: 2049 of 2100
iteration: 2050 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2051 of 2100
iteration: 2052 of 2100
iteration: 2053 of 2100
iteration: 2054 of 2100
iteration: 2055 of 2100
iteration: 2056 of 2100
iteration: 2057 of 2100
iteration: 2058 of 2100
iteration: 2059 of 2100
iteration: 2060 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2061 of 2100
iteration: 2062 of 2100
iteration: 2063 of 2100
iteration: 2064 of 2100
iteration: 2065 of 2100
iteration: 2066 of 2100
iteration: 2067 of 2100
iteration: 2068 of 2100
iteration: 2069 of 2100
iteration: 2070 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2071 of 2100
iteration: 2072 of 2100
iteration: 2073 of 2100
iteration: 2074 of 2100
iteration: 2075 of 2100
iteration: 2076 of 2100
iteration: 2077 of 2100
iteration: 2078 of 2100
iteration: 2079 of 2100
iteration: 2080 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2081 of 2100
iteration: 2082 of 2100
iteration: 2083 of 2100
iteration: 2084 of 2100
iteration: 2085 of 2100
iteration: 2086 of 2100
iteration: 2087 of 2100
iteration: 2088 of 2100
iteration: 2089 of 2100
iteration: 2090 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4

iteration: 2091 of 2100
iteration: 2092 of 2100
iteration: 2093 of 2100
iteration: 2094 of 2100
iteration: 2095 of 2100
iteration: 2096 of 2100
iteration: 2097 of 2100
iteration: 2098 of 2100
iteration: 2099 of 2100
iteration: 2100 of 2100

     criterion  nEstimators  maxDepth  maxFeatures  trainScore  testScore
1159   entropy           10         7            2    0.748156        0.5
707    entropy           11         7            3    0.747837        0.5
1956  log_loss           10         6            2    0.747731        0.5
494   log_loss           11         7            2    0.887517        0.4
179       gini           10         6            3    0.822242        0.4
...        ...          ...       ...          ...         ...        ...
132       gini           12         6            2    0.744143        0.0
1310   entropy           10         6            2    0.743409        0.0
1516  log_loss           11         6            2    0.743095        0.0
1730  log_loss           11         6            2    0.742458        0.0
1237      gini           11         6            2    0.742415        0.0

[2100 rows x 6 columns]

best model found